### ISSUE TITLE
在运行sh scripts/promptkd/base2new_train.sh imagenet 3时，显示报错如下，test数据加载不进来，train数据可以加载进来，恳求解决方案，谢谢

### ISSUE THREAD

**Issue by XiaozhenQiao** [zhengli97/PromptKD#17]
Traceback (most recent call last):
  File "/nvfile-data/qxz/project/VQA/PromptKD/train.py", line 273, in <module>
    main(args)
  File "/nvfile-data/qxz/project/VQA/PromptKD/train.py", line 204, in main
    trainer = build_trainer(cfg)
  File "/nvfile-data/qxz/project/VQA/PromptKD/Dassl/dassl/engine/build.py", line 11, in build_trainer
    return TRAINER_REGISTRY.get(cfg.TRAINER.NAME)(cfg)
  File "/nvfile-data/qxz/project/VQA/PromptKD/Dassl/dassl/engine/trainer.py", line 324, in __init__
    self.build_data_loader()
  File "/nvfile-data/qxz/project/VQA/PromptKD/Dassl/dassl/engine/trainer.py", line 347, in build_data_loader
    dm = DataManager(self.cfg)
  File "/nvfile-data/qxz/project/VQA/PromptKD/Dassl/dassl/data/data_manager.py", line 130, in __init__
    test_loader = build_data_loader(
  File "/nvfile-data/qxz/project/VQA/PromptKD/Dassl/dassl/data/data_manager.py", line 44, in build_data_loader
    assert len(data_loader) > 0
AssertionError

**Comment by zhengli97** [comment]
你这个看起来应该是路径或者文件没放对，触发了assert len(data_loader)>0，就是你自己数据集存放的问题，没读起来

**Comment by XiaozhenQiao** [comment]
![1](https://github.com/user-attachments/assets/4db722ee-eff8-40fd-9f15-84750e38a47d)
![2](https://github.com/user-attachments/assets/b15c9dc0-3fef-463d-88af-7e5e000828ae)

**Comment by XiaozhenQiao** [comment]
您好，我的这个文件放置感觉没问题呀，train和val在一级目录下，而且能够读取train数据集呀

**Comment by XiaozhenQiao** [comment]
![3](https://github.com/user-attachments/assets/91bf0761-17f5-4e51-8337-948fcf129db1)
val文件夹下面是50000张图片

**Comment by zhengli97** [comment]
![image](https://github.com/user-attachments/assets/6221e991-cdc2-4438-b1e5-493414446aeb)
![image](https://github.com/user-attachments/assets/10fcc8c3-c7d2-42cf-8723-f0f079027275)
val应该是这样的

**Comment by XiaozhenQiao** [comment]
好嘞，谢谢您的耐心回复

**Comment by zhengli97** [comment]
@XiaozhenQiao 最近我跑imagenet的实现，发现了一个对你现在情况的一个解决办法，你可以看一下这个，用valprep.sh脚本来处理文件，把val文件都放进文件夹里 https://github.com/soumith/imagenetloader.torch/blob/master/valprep.sh

**Comment by zhengli97** [comment]
@sodawithbubbles   👍👍👍
